name: build documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Pylossless
        run: |
          pip install --upgrade pip
          pip install -e .
      
      - name: Install testing dependencies
        run: pip install -r requirements_testing.txt

      - name: Install doc dependencies
        run: pip install -r docs/requirements_doc.txt

      - name: Build documentation
        run: |
          cd docs
          make html
