name: build documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Pylossless
        run: pip install -e .

      - name: install openneuro-py
        run: pip install openneuro-py

      - name: Install doc dependencies
        run: pip install -r docs/requirements_doc.txt

      - name: Build documentation
        run: |
          cd docs
          make html
